### ISSUE TITLE
File does not exist

### ISSUE THREAD

**Issue by p3palazzo** [Myllaume/eleventy-plugin-citeproc#3]
Is this plugin compatible with Eleventy v2? I'm getting `File /path/to/style.csl does not exist` even though the file is exactly where the plugin is complaining that it isn't. Full trace here:

```
[11ty] Eleventy CLI Fatal Error: (more in DEBUG output)
[11ty] 1. Error processing a plugin (via EleventyPluginError)
[11ty] 2. File /full/path/to/repository/assets/biblio/chicago-note-bibliography.csl does not exists. (via Error)
[11ty]
[11ty] Original error stack trace: Error: File /full/path/to/repository/assets/biblio/chicago-note-bibliography.csl does not exists.
[11ty]     at module.exports (/full/path/to/repository/node_modules/eleventy-plugin-citeproc/src/csl.js:33:19)
[11ty]     at module.exports (/full/path/to/repository/node_modules/eleventy-plugin-citeproc/index.js:12:17)
[11ty]     at UserConfig._executePlugin (/full/path/to/repository/node_modules/@11ty/eleventy/src/UserConfig.js:386:7)
[11ty]     at TemplateConfig.processPlugins (/full/path/to/repository/node_modules/@11ty/eleventy/src/TemplateConfig.js:254:25)
[11ty]     at TemplateConfig.mergeConfig (/full/path/to/repository/node_modules/@11ty/eleventy/src/TemplateConfig.js:367:10)
[11ty]     at TemplateConfig.getConfig (/full/path/to/repository/node_modules/@11ty/eleventy/src/TemplateConfig.js:159:26)
[11ty]     at new Eleventy (/full/path/to/repository/node_modules/@11ty/eleventy/src/Eleventy.js:109:39)
[11ty]     at Object.<anonymous> (/full/path/to/repository/node_modules/@11ty/eleventy/cmd.js:60:16)
[11ty]     at Module._compile (node:internal/modules/cjs/loader:1378:14)
[11ty]     at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
(node:28529) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

The style is freshly downloaded from the CSL/styles repository with no modifications, by the way.

**Comment by Myllaume** [comment]
It is not compatible with Eleventy v.2.
I will see to update it. 😄
